//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Point24.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_POINT24_DIALOG              102
#define IDR_MAINFRAME                   128
#define IDB_BACK                        129
#define IDB_FP1                         131
#define IDB_FP2                         132
#define IDB_FP3                         133
#define IDB_FP4                         134
#define IDB_FP5                         135
#define IDB_FP6                         136
#define IDB_FP7                         137
#define IDB_FP8                         138
#define IDB_FP9                         139
#define IDB_FP10                        140
#define IDB_FP11                        141
#define IDB_FP12                        142
#define IDB_FP13                        143
#define IDB_HT1                         144
#define IDB_HT2                         145
#define IDB_HT3                         146
#define IDB_HT4                         147
#define IDB_HT5                         148
#define IDB_HT6                         149
#define IDB_HT7                         150
#define IDB_HT8                         151
#define IDB_HT9                         152
#define IDB_HT10                        153
#define IDB_HT11                        154
#define IDB_HT12                        155
#define IDB_HT13                        156
#define IDB_HTT1                        157
#define IDB_HTT2                        158
#define IDB_HTT3                        159
#define IDB_HTT4                        160
#define IDB_HTT5                        161
#define IDB_HTT6                        162
#define IDB_HTT7                        163
#define IDB_HTT8                        164
#define IDB_HTT9                        165
#define IDB_HTT10                       166
#define IDB_HTT11                       167
#define IDB_HTT12                       168
#define IDB_HTT13                       169
#define IDB_MH1                         170
#define IDB_MH2                         171
#define IDB_MH3                         172
#define IDB_MH4                         180
#define IDB_MH5                         181
#define IDB_MH6                         182
#define IDB_MH7                         183
#define IDB_MH8                         184
#define IDB_MH9                         185
#define IDB_MH10                        186
#define IDB_MH11                        187
#define IDB_MH12                        188
#define IDB_MH13                        189
#define IDR_MENU                        190
#define IDC_START                       1000
#define IDC_EDIT1                       1001
#define IDC_INPUT                       1004
#define IDC_CALC                        1013
#define IDC_PROGRESS                    1014
#define IDC_COMBO                       1015
#define IDC_LIST                        1022
#define IDC_CUR_SCORE                   1023
#define IDD_ABOUT                       32774

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        192
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         1024
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
